project:
  type: book

book:
  title: "TFG"
  author: "Vera Gómez-Limón Gallardo"
  date: last-modified
  chapters:
    - index.qmd
    - intro.qmd
    - abstract.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: default



