project:
  type: book
  output-dir: _book
  preview: 
    port: 4200

book:
  output-file: "thesis"
  title: "Compostable Plastics Contribute to the Pollution of the Ocean"
  subtitle: "An experimental approach to the potential biodegradability of bioplastic material in the marine environment"
  genre: "Degree in Marine Sciences Final Thesis"
  author:
    name: "Vera Gómez-Limón Gallardo"
    email: "vera.gomez101@alu.ulpgc.es"
  date: last-modified
  chapters:
    - index.qmd
    - abstract.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - conclusion.qmd
    - thanks.qmd
    - references.qmd

bibliography: _refs.bib

format: html

execute: 
  freeze: auto
  echo: false

