project:
  type: book

book:
  title: "Degree in Marine Sciences final Thesis"
  output-file: "thesis"
  subtitle: "Bioplastics as a possible solution to plastic pollution in the ocean"
  author:
    name: "Vera Gómez-Limón Gallardo"
    email: "vera.gomez101@alu.ulpgc.es"
  date: last-modified
  chapters:
    - index.qmd
    - abstract.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - conclusions.qmd
    - thanks.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
  docx: default

execute: 
  freeze: auto
  echo: false

